---
type: gui
log:
    version: 1
    formatters:
        console_formatter:
            format: "[%(asctime)s %(levelname)s %(name)s] %(message)s"
        default: {}
    handlers:
        console_handler:
            class: logging.StreamHandler
            formatter: console_formatter
            level: DEBUG
        syslog:
            class: hat.syslog.handler.SysLogHandler
            host: localhost
            port: 6514
            comm_type: TCP
            level: INFO
            formatter: default
            queue_size: 50
            filters: []
    root:
        level: INFO
        handlers: ['syslog']
        # handlers: ['console_handler', 'syslog']
adapters:
  - name: my_adapter
    module: adapters.simple_adapter
    subscriptions:
      - ['modbus_module', '?', 'read_result', 'counter', '?']
      - ['modbus_module', '?', 'manual_read_result', 'counter', '?']
    items:
      - key: device_1_counter_1
        event_type: ['modbus_module', 'my_device', 'manual_read_result', 'counter', '1']
      - key: device_1_counter_2
        event_type: ['modbus_module', 'my_device', 'manual_read_result', 'counter', '2']
      - key: device_2_counter_1
        event_type: ['modbus_module', 'my_device_2', 'manual_read_result', 'counter', '1']
      - key: device_2_counter_2
        event_type: ['modbus_module', 'my_device_2', 'manual_read_result', 'counter', '2']

views: []
address: "http://localhost:23023"
initial_view: null
users:
  - name: user1
    password:  # pass1
        hash: '4f51b0a300aeadf7f13d87e43eb48f8d95149efa7dde614194b4aa1e116bf078'
        salt: 'a8534416dc3caca0ec6f4f1a298ead2c'
    roles:
        - admin
    view: null
event_server_address: 'tcp+sbs://localhost:23012'
...