---
"$schema": "http://json-schema.org/schema#"
id: 'my_stuff://everything/modules/modbus_enabler/schema.yaml#'
type: object
required:
    - device_types
properties:
    device_types:
        type: array
...